### ISSUE TITLE
Cannot read properties of undefined (reading 'type') HmIPWallMountedThermostat

### ISSUE THREAD

**Issue by dostra7** [marcsowen/homebridge-homematicip#433]
Hi,
I set up a homebridge system, but service is being stopped as the server is in a shutting-donw-restarting loop.
it says:

 TypeError: Cannot read properties of undefined (reading 'type')
    at HmIPWallMountedThermostat.updateDevice (/var/lib/homebridge/node_modules/homebridge-homematicip/src/devices/HmIPWallMountedThermostat.ts:250:31)
    at new HmIPWallMountedThermostat (/var/lib/homebridge/node_modules/homebridge-homematicip/src/devices/HmIPWallMountedThermostat.ts:72:10)
    at HmIPPlatform.updateAccessory (/var/lib/homebridge/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:268:28)
    at HmIPPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:156:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

copy from the log:
[25/03/2023, 21:42:31] [HomematicIP] Target temperature of Temperatur- und Luftfeuchtigkeitssensor Keller Küche  changed to 21 °C (device channel)
[25/03/2023, 21:42:31] TypeError: Cannot read properties of undefined (reading 'type')
    at HmIPWallMountedThermostat.updateDevice (/var/lib/homebridge/node_modules/homebridge-homematicip/src/devices/HmIPWallMountedThermostat.ts:250:31)
    at new HmIPWallMountedThermostat (/var/lib/homebridge/node_modules/homebridge-homematicip/src/devices/HmIPWallMountedThermostat.ts:72:10)
    at HmIPPlatform.updateAccessory (/var/lib/homebridge/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:268:28)
    at HmIPPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:156:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[25/03/2023, 21:42:31] Got SIGTERM, shutting down Homebridge...
[25/03/2023, 21:42:31] [HomematicIP] HmIP websocket shutdown...
[25/03/2023, 21:42:36] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[25/03/2023, 21:42:41] [HB Supervisor] Restarting Homebridge...
[25/03/2023, 21:42:41] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[25/03/2023, 21:42:41] [HB Supervisor] Started Homebridge v1.5.1 with PID: 1630
[25/03/2023, 21:42:42] Loaded config.json with 0 accessories and 2 platforms.
[25/03/2023, 21:42:42] Loaded 45 cached accessories from cachedAccessories.
[25/03/2023, 21:42:43] ---
[25/03/2023, 21:42:45] Loaded plugin: homebridge-homematicip@1.1.0
[25/03/2023, 21:42:45] Registering platform 'homebridge-homematicip.HomematicIP'

the device should be supported, correct?
What can I do?

**Comment by marcsowen** [comment]
This crash was caused by dereferencing a heating-group reference that was absent from the returned groups. The current implementation checks and validates the referenced group before using it. Fixed as part of the v2.0.0 rewrite. Please reopen or create a new issue if it still occurs with the latest release.
