### ISSUE TITLE
Support for Node 20.9.0

### ISSUE THREAD

**Issue by GoekhanYilmaz** [marcsowen/homebridge-homematicip#445]
seems like its not working with node 20.9.0. Following log appears and homebridge keeps looping the restart: 

TypeError: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:406:5)
    at Proxy.has (node:internal/url:546:13)
    at Proxy.<anonymous> (C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\node_modules\node-fetch\src\headers.js:128:44)
    at new Request (C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\node_modules\node-fetch\src\request.js:71:38)
    at C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\node_modules\node-fetch\src\index.js:37:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\node_modules\node-fetch\src\index.js:35:9)
    at HmIPConnector.init (C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\src\HmIPConnector.ts:114:33)
    at HmIPPlatform.startPairing (C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\src\HmIPPlatform.ts:104:32)
    at HomebridgeAPI.<anonymous> (C:\Users\remotedesktop\AppData\Roaming\npm\node_modules\homebridge-homematicip\src\HmIPPlatform.ts:81:14)

**Comment by Themaster312** [comment]
Same Problem

**Comment by reinisb** [comment]
Same problem, after update to Node 20.9.0 Homebridge Homematicip stopped working and is crashing the entire Homebridge instance. @marcsowen can you please fix?

**Comment by MarshallErPunkt** [comment]
Same Problem

**Comment by marcsowen** [comment]
Please try version 1.2.0 (beta).

**Comment by GoekhanYilmaz** [comment]
> Please try version 1.2.0 (beta).

just installed and tried. Seems to work now. No issues so far. Thanks a lot!

**Comment by Themaster312** [comment]
Thanks it Works

**Comment by reinisb** [comment]
Thanks, worked for me as well.
