### ISSUE TITLE
TypeError: The "listener"

### ISSUE THREAD

**Issue by tobias406** [marcsowen/homebridge-homematicip#447]
Hi,

after the update to 1.20 i have the following issue

 TypeError: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:274:3)
    at ClientRequest.once (node:events:648:3)
    at new ClientRequest (node:_http_client:239:10)
    at Object.request (node:https:378:10)
    at /usr/local/lib/node_modules/homebridge-broadband/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22
    at file:///usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:94:20
    at new Promise (<anonymous>)
    at fetch (file:///usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:49:9)
    at HmIPConnector.init (file:///usr/local/lib/node_modules/homebridge-homematicip/src/HmIPConnector.ts:114:28)
    at HmIPPlatform.discoverDevices (file:///usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:146:32)

Does someone have an answer how to fix? 
Thanks

**Comment by marcsowen** [comment]
Which node.js version are you using?

**Comment by tobias406** [comment]
i have updatet to the latest version

**Comment by marcsowen** [comment]
Actually, I don't know what the problem is. Somehow an issue related to the node-fetch library not being compatible with your node.js version. Maybe try to remove the plugin completely and try again, e.g. the directory /usr/local/lib/node_modules/homebridge-homematicip - You can of course keep your configuration.

If possible write down the exact version of node.js and maybe the node-fetch library in /usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch
