### ISSUE TITLE
Error in HmIP-BSL Set Callback Handlers

### ISSUE THREAD

**Issue by smhex** [marcsowen/homebridge-homematicip#557]
I noticed that some of my HmIP-BSL scenes do not work anymore. I am not sure since when this has happened. Switching on the DEBUG mode I have seen the following error messages for all characteristics (On, Hue, Brightness, Saturation) which are modified in a specific scene:

```
[6/23/2024, 11:24:47 AM] [homebridge-homematicip] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[6/23/2024, 11:24:47 AM] [homebridge-homematicip] Error: 
    at On.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2632:22
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at HmIPSwitchNotificationLight.handleButton1LedBrightnessSet (file:///homebridge/node_modules/homebridge-homematicip/src/devices/HmIPSwitchNotificationLight.ts:218:5)
    at HmIPSwitchNotificationLight.handleButton1LedOnSet (file:///homebridge/node_modules/homebridge-homematicip/src/devices/HmIPSwitchNotificationLight.ts:196:7)
```

I will spent some more time to investigate here...

**Comment by gkminix** [comment]
No need to investigate. The BSL switches got a new firmware which requires a significant rewrite of the code. I have released a couple of patches to the code, which you can get the via github. Marc was so kind to include them into his source code . If possible, do also merge my latest commits which fix a couple of bugs.

**Comment by smhex** [comment]
Thanks, I will update my installation as soon as Marc has merged your PR's.

**Comment by jochencschmidt** [comment]
Any progress on this issue? I'm using Homebridge v 1.9.0 and homebridge-homematicip v 1.3.1 and try to control a HmIP-BSL switch (notification lights) via HomeKit. Currently, the notification lights show pretty erratic behavior. Colors do not match, switching on works from time to time both mostly not. I would be really happy if there was some update or fix to help with that. Thanks!

**Comment by gkminix** [comment]
You need to use the current github version. Marc hasn't released a new package yet. Alternatively, you can use my fork if you like: https://github.com/gkminix/homebridge-homematicip. It contains my latest patches regarding HmIP-BSL.

**Comment by marcsowen** [comment]
Is this still an issue?

**Comment by jochencschmidt** [comment]
I honestly can't tell. I switched away from that setup (was never working as intended) quite a while ago. Sorry.

**Comment by marcsowen** [comment]
Ok, I will close this issue for now. If there are further problems, please open up a new ticket.
